### ISSUE TITLE
Firebase Storage: Invalid argument in `put` at index 0: Expected Blob or File

### ISSUE THREAD

**Issue by fangqiank** [iamshaunjp/firegram#3]
<img width="772" alt="screencapture" src="https://user-images.githubusercontent.com/1538782/89109282-fee71d80-d3fc-11ea-87f0-36ec70227139.png">

**Comment by fangqiank** [comment]
In the component 'uploadForm':

`if (selected && types.includes(selected.type)) {
      setFile(selected);
      console.log(file instanceof File);
      setErr("");
    } else {
      setFile(null);
      setErr("Please select an image file (png or jpg)");
    }
  };`

<img width="781" alt="截屏2020-08-01 下午1 46 32" src="https://user-images.githubusercontent.com/1538782/89109362-b9772000-d3fd-11ea-9a8b-7086cd21b8e7.png">

**Comment by lucasbarroso23** [comment]
Hello, i had this error and the problem for me was:
 i set up the wrong database in the firebase, instead of setting up the "Cloud firestore" i did it with the "Realtime Database", so i just initialized a database in the right one and worked just fine.

**Comment by m2paulc** [comment]
Getting this error now when adding the document to a collection. 
Would this be related to a firebase promise?
rules are to allow anyone to read and write.

`index.js:1 Uncaught Error in onSnapshot: FirebaseError: Missing or insufficient permissions.
    at new n (http://localhost:3000/static/js/0.chunk.js:12316:19)
    at http://localhost:3000/static/js/0.chunk.js:23499:18
    at http://localhost:3000/static/js/0.chunk.js:23500:10
    at n.onMessage (http://localhost:3000/static/js/0.chunk.js:23548:6)
    at http://localhost:3000/static/js/0.chunk.js:23411:18
    at http://localhost:3000/static/js/0.chunk.js:23449:29
    at http://localhost:3000/static/js/0.chunk.js:20931:25`
